/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/crt_tv.glb 
Author: Timothy Ahene (https://sketchfab.com/timothyahene)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/crt-tv-9ba4baa106e64319a0b540cf0af5aa9e
Title: CRT TV
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/crt_tv.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 26.836, 0]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.TVback} position={[0, -0.042, 0]} scale={[0.99, 0.99, 1]} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.TVfront} />
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.TVfront} />
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.TVScreen} position={[0, 0, -166.617]} scale={398.216} />
            <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.TVfront} position={[3.169, -20.046, -18.301]} rotation={[0, 0, -0.596]} scale={[0.378, 0.378, 0.221]} />
            <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.TVfront} position={[0, -26.836, 0]} />
            <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.TVfront} position={[11.057, -26.295, -18.646]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.TVfront} position={[26.908, -17.616, -17.225]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.173, 0.159, 0.173]} />
            <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.TVfront} position={[0.003, -19.835, 0.852]} scale={0.11} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/crt_tv.glb')
